# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  self-build:
    name: Self-Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Build Thyself
        env:
          SEMATEXT_API_KEY: ${{ secrets.SEMATEXT_API_KEY }}
          SEMATEXT_APP_TOKEN: ${{ secrets.SEMATEXT_APP_TOKEN }}
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: |
          set -euo pipefail
          touch .env
          ./build-version.sh cross
      - name: Install Thyself
        run: cargo install --path cargo-quickinstall
      - name: Install Thyself with Thyself
        run: cargo quickinstall cargo-quickinstall
